name: 'Trunk-based Development Processor'
description: 'Multipurpose GitHub Action'
inputs:
  release_type:
    description: 'Release type (major, minor, patch)'
    required: true
    default: 'patch'
  docs_dir:
    description: 'Default directory for changelogs'
    required: false
    default: 'docs'
  config_dir:
    description: 'Default directory for git-chglog configuration'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Create release branch
      shell: bash
      id: app_release
      run: ${{ github.action_path }}/../../scripts/init_app_release.sh "${{ inputs.release_type }}"
    - name: Cleanup previous release notes
      shell: bash
      run: git rm --ignore-unmatch "${{ inputs.docs_dir }}/chglog/release-notes*"
    - name: Generate Release Notes
      uses: docker://quay.io/git-chglog/git-chglog:latest
      env:
        VERSION: ${{ steps.app_release.outputs.new_version }}
        CONFIG_PATH: ${{ inputs.config_dir }}/.chglog/config.yml
        OUTPUT_PATH: ${{ inputs.docs_dir }}/chglog/release-notes-${{ steps.app_release.outputs.new_version }}.md
      with:
        args: -c "${{ env.CONFIG_PATH }}" -o "${{ env.OUTPUT_PATH }}" --next-tag "${{ env.VERSION }}" "${{ env.VERSION }}"
    ###
    ### Do not move the following bash script into file, because previous script manipulates with the release branches
    ### which can cause replacement of the initial init_app_release.sh content
    ###
    - name: Commit and push changes to release branch
      shell: bash
      run: |
        git add "${{ inputs.docs_dir }}/*"
        git commit -m "Generate release notes and documentation for $(git branch --show-current)"
        git push --set-upstream origin "$(git branch --show-current)"
