name: 'Repo Dispatch'
description: 'Repository Dispatch GitHub Action'
inputs:
  event_type:
    description: 'Event Type'
    required: true
  client_payload:
    description: 'Client Payload'
    default: '{}'
    required: false
  repository:
    description: ''
    required: false
runs:
  using: "composite"
  steps:
    - name: Run Repo Workflow
      shell: bash
      env:
        REPO: ${{ inputs.repository || github.repository }}
      run: |
        gh api "repos/${{ env.REPO }}/dispatches" \
            --raw-field "event_type=${{ inputs.event_type }}"
