name: 'Container operations'
description: ' Build and Publish Docker image for applications packaged as docker artifact'

inputs:
  push_image:
    description: 'Whether to push image to Docker Registry or not?'
    required: true
    default: 'false'
  container_dir:
    description: 'Container directory'
    required: false
    default: 'infra/'
  build_context:
    description: 'Image build context'
    required: false
    default: '.'
  app_config_file:
    description: "App config file location"
    required: false
    defaul: '${GITHUB_WORKSPACE}/${CONTAINER_DIR}app.conf'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Container Operations"
          ${{ github.action_path }}/../../scripts/container_ops.sh \
             "${{ inputs.push_image }}" \
             "${{ inputs.container_dir }}" \
             "${{ inputs.build_context }}" \
             "${{ inputs.app_config_file }}"
        echo "::endgroup::"
