name: 'Container operations'
description: ' Build and Publish Docker image for applications packaged as docker artifact'

inputs:
  push_image:
    description: 'Whether to push image to Docker Registry or not?'
    required: true
    default: 'false'


runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Container Operations"
          ${{ github.action_path }}/../../scripts/container_ops.sh \
             "${{ inputs.push_image }}"
        echo "::endgroup::"