name: Comment PR

on:
  workflow_call:

jobs:
  comment-pr:
    name: Comment PR
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        id: comment_pr
        uses: htec-infra/gha-utils/utils/comment-pr@VERSION
        with:
          token: "${{ env.GITHUB_TOKEN }}"