name: GitHub Release
on:
  repository_dispatch:
    types: [ new_github_release ]
    # inputs
    #    version: <semantic>
    #    revision: <git-sha>

jobs:
  publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - name: Create Release
          uses: htec-infra/gha-utils/actions/gh-release@VERSION
          with:
            app_version: ${{ github.event.client_payload.version }} # optional
            app_revision:  ${{ github.event.client_payload.revision }} # optional
