name: "Repository data"
description: "Fetch repository and organization name"

inputs:
  container_dir:
    description: "Container config directory"
    required: false
    default: "infra/"
  custom_prefix:
    description: "Custom prefix for APP_VERSION"
    required: false
    default: ""

outputs:
  repo_name:
    description: "Repository name"
    value: ${{ steps.repo_data.outputs.APP_REPO_NAME }}
  org_name:
    description: "Organization name"
    value: ${{ steps.repo_data.outputs.APP_REPO_ORG }}
  app_version:
    description: "Application version"
    value: ${{ steps.repo_data.outputs.APP_VERSION }}
  app_revision:
    description: "Application revision"
    value: ${{ steps.repo_data.outputs.APP_REVISION }}
  app_release_type:
    description: "Application release type"
    value: ${{ steps.repo_data.outputs.APP_RELEASE_TYPE }}
  container_repo:
    description: "Docker repository"
    value: ${{ steps.repo_data.outputs.CONTAINER_REPO }}
  branch_ref:
    description: "Branch reference"
    value: ${{ steps.repo_data.outputs.GITHUB_REF }}
  head_branch_ref:
    description: "Head branch reference"
    value: ${{ steps.repo_data.outputs.GITHUB_HEAD_REF }}
  repo_summary:
    description: "Repo summary"
    value: ${{ steps.repo_data.outputs.REPO_SUMMARY }}

runs:
  using: "composite"
  steps:
    - id: repo_data
      shell: bash
      run: ${{ github.action_path }}/../../scripts/repo_data.sh "${{ inputs.container_dir }}" "${{ inputs.custom_prefix }}"
