name: 'Container operations'
description: 'Publish comment on PR'

inputs:
  github_token:
    description: 'Github access token'
    required: true
  message:
    description: 'Repo summary'
    required: false

runs:
  using: "composite"
  steps:
    - id: Prepare content
      shell: bash
      run: |
        if [[ -n "${{ inputs.message }}" ]]; then
          echo "Comment body provided"
        else
          echo "PR comment not provided. Running 'repo_data' script to generate REPO_SUMMARY"
          ${{ github.action_path }}/../../scripts/repo_data.sh
        fi
    - name: Comment PR
      uses: actions/github-script@v6
      env:
        PR_MSG: ${{ inputs.message || steps.repo_data.outputs.REPO_SUMMARY }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { GITHUB_ACTION_PATH, PR_MSG } = process.env
          const script = require(`${GITHUB_ACTION_PATH}/../../scripts/comment_pr.js`)
          await script({github, context, pr_msg: PR_MSG})
